// Generates TS piece-set modules from downloaded lichess SVGs.
// - Extracts inner SVG content + viewBox
// - Namespaces ids (merida uses gradient ids that collide when inlined)
// - Derives a gold "gilded" colorway from cburnett
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, 'pieces');
const OUT = join(ROOT, '..', 'src', 'lib', 'piece-sets');
mkdirSync(OUT, { recursive: true });

const PIECES = ['wK', 'wQ', 'wR', 'wB', 'wN', 'wP', 'bK', 'bQ', 'bR', 'bB', 'bN', 'bP'];

function extract(svgText, nsPrefix) {
  const viewBox = svgText.match(/viewBox="([^"]+)"/)?.[1] ?? '0 0 45 45';
  let inner = svgText.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
  // Namespace ids and their references
  inner = inner.replace(/id="([^"]+)"/g, `id="${nsPrefix}-$1"`);
  inner = inner.replace(/url\(#([^)]+)\)/g, `url(#${nsPrefix}-$1)`);
  inner = inner.replace(/xlink:href="#([^"]+)"/g, `xlink:href="#${nsPrefix}-$1"`);
  inner = inner.replace(/href="#([^"]+)"/g, `href="#${nsPrefix}-$1"`);
  return { viewBox, inner };
}

function gild(inner, isWhite) {
  if (isWhite) {
    return inner
      .replaceAll('#fff', '#E9CD79')
      .replaceAll('#ffffff', '#E9CD79')
      .replaceAll('#000', '#4A3408')
      .replaceAll('#000000', '#4A3408');
  }
  return inner
    .replace(/fill="#000(000)?"/g, 'fill="#14100A"')
    .replace(/stroke="#000(000)?"/g, 'stroke="#B9912F"')
    .replaceAll('#fff', '#D4AF4F')
    .replaceAll('#ffffff', '#D4AF4F');
}

function buildSet(setDir, nsBase) {
  const pieces = {};
  let viewBox = '0 0 45 45';
  for (const p of PIECES) {
    const text = readFileSync(join(SRC, setDir, `${p}.svg`), 'utf8');
    const { viewBox: vb, inner } = extract(text, `${nsBase}-${p.toLowerCase()}`);
    viewBox = vb;
    pieces[p.toLowerCase()] = inner;
  }
  return { viewBox, pieces };
}

function emit(file, constName, comment, set) {
  const entries = Object.entries(set.pieces)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join('\n');
  const src = `// AUTO-GENERATED by .assets/gen-pieces.mjs — do not edit by hand.
// ${comment}
import type { PieceSvgData } from './types';

export const ${constName}: PieceSvgData = {
  viewBox: ${JSON.stringify(set.viewBox)},
  pieces: {
${entries}
  },
};
`;
  writeFileSync(join(OUT, file), src);
  console.log(`wrote ${file} (${src.length} bytes)`);
}

const cburnett = buildSet('cburnett', 'cb');
emit('cburnett.ts', 'CBURNETT', 'Pieces by Colin M.L. Burnett (cburnett), CC BY-SA 3.0 — via lichess-org/lila.', cburnett);

const gilded = {
  viewBox: cburnett.viewBox,
  pieces: Object.fromEntries(
    Object.entries(cburnett.pieces).map(([k, v]) => [
      k,
      gild(v.replaceAll('id="cb-', 'id="gd-').replaceAll('url(#cb-', 'url(#gd-').replaceAll('href="#cb-', 'href="#gd-'), k.startsWith('w')),
    ])
  ),
};
emit('gilded.ts', 'GILDED', 'Gold colorway derived from cburnett pieces (CC BY-SA 3.0).', gilded);

const merida = buildSet('merida', 'mr');
emit('merida.ts', 'MERIDA', 'Merida pieces by Armando Hernandez Marroquin (freeware) — via lichess-org/lila.', merida);
